name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      if: ${{contains(toJson(github.event.commits[0].message), '#skip') == false}}
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        
  a_test_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits[0].message) }}
        run: echo "$COMMIT_MESSAGES"
