name: Bump version
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: commit messages
      env:
        COMMIT_MESSAGES: ${{ toJson(github.event.commits[0].message) }}
      run: echo "$COMMIT_MESSAGES"  
